# Generated by Django 5.2.8 on 2025-12-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_galleryimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('session_key', 'date')},
            },
        ),
    ]
