# Generated by Django 5.2.8 on 2026-01-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_contactmessage_options_contactmessage_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
