"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent


# ======================
# SECURITY
# ======================
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-b6wacfie&7v$qwvkeq*e+k)kt27d$wu_1+q(=)jl=fs8pu9y*!",
)
DEBUG = True
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


# ======================
# APPLICATIONS
# ======================
INSTALLED_APPS = [
    "jazzmin",  # ✅ MUST BE BEFORE ADMIN
    
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "listings",
    'pages',
    "accounts.apps.AccountsConfig",
]

# ======================
# JAZZMIN ADMIN CONFIGURATION
# ======================
JAZZMIN_SETTINGS = {
    # Title on the login screen
    "site_title": "Scholarify Admin",
    
    # Title on the brand (19 chars max)
    "site_header": "Scholarify",
    
    # Welcome text on the login screen
    "welcome_sign": "Welcome to Scholarify Admin Portal",
    
    # Copyright on the footer
    "copyright": "Scholarify © 2024",
    
    # Logo to use for your site
    # "site_logo": "images/logo.png",
    
    # ======================
    # SIDEBAR CONFIGURATION
    # ======================
    "show_sidebar": True,
    "navigation_expanded": False,
    
    # ======================
    # SIDEBAR ICONS
    # ======================
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "listings.Listing": "fas fa-newspaper",
        "pages.ContactMessage": "fas fa-envelope",
        "pages.GalleryImage": "fas fa-images",
        "pages.GalleryLike": "fas fa-heart",
        "pages.SiteVisit": "fas fa-chart-bar",
    },
    
    # ======================
    # DEFAULT ICONS
    # ======================
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    # ======================
    # UI CUSTOMIZATION
    # ======================
    "theme": "default",
    
    # ======================
    # TOP MENU
    # ======================
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Visit Site", "url": "/", "new_window": True},
        {"model": "auth.user"},
        {"app": "listings"},
        {"app": "pages"},
    ],
    
    # ======================
    # CHANGE FORM SETTINGS
    # ======================
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    
    # ======================
    # RELATED MODAL SETTINGS
    # ======================
    "related_modal_active": True,
}

# ======================
# JAZZMIN UI TWEAKS
# ======================
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success"
    }
}

# ======================
# MIDDLEWARE
# ======================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # For language switching
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'pages.middleware.SiteVisitMiddleware',
]

# ======================
# URLS / TEMPLATES
# ======================
ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pages.context_processors.site_stats',
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# ======================
# DATABASE (PostgreSQL)
# ======================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "nextstep_DB",
        "USER": "postgres",
        "PASSWORD": "Hmis@123",
        "HOST": "localhost",
        "PORT": "5432",
    }
}

# ======================
# EMAIL CONFIGURATION
# ======================
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "attatabey3@gmail.com"
EMAIL_HOST_PASSWORD = "hsbjfvonouoyzink"
DEFAULT_FROM_EMAIL = "Scholarify <attatabey3@gmail.com>"
CONTACT_RECEIVER_EMAIL = "attatabey3@gmail.com"
SERVER_EMAIL = "server@scholarify.com"

# Site info for password reset emails
SITE_ID = 1
SITE_NAME = "Scholarify"
SITE_URL = "http://localhost:8000"  # For development

# ======================
# PASSWORD VALIDATION
# ======================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ======================
# INTERNATIONALIZATION (EN + PASHTO)
# ======================
LANGUAGE_CODE = "en"

# Custom language support for Pashto
import django.conf.locale
EXTRA_LANG_INFO = {
    'ps': {
        'bidi': True,
        'code': 'ps',
        'name': 'Pashto',
        'name_local': 'پښتو',
    }
}
django.conf.locale.LANG_INFO.update(EXTRA_LANG_INFO)

LANGUAGES = [
    ("en", _("English")),
    ("ps", _("Pashto")),
]

USE_I18N = True
USE_L10N = True

# Translation files location
LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = "Asia/Kabul"
USE_TZ = True

# ======================
# STATIC & MEDIA FILES
# ======================
STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ======================
# AUTHENTICATION
# ======================
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# ======================
# SESSION SETTINGS
# ======================
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_SAVE_EVERY_REQUEST = True

# ======================
# DEFAULT PK
# ======================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ======================
# LOGGING (Optional)
# ======================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}