"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _
import dj_database_url
import django.conf.locale

# ----------------------
# BASE DIR
# ----------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------
# SECURITY (ENV BASED)
# ----------------------
# IMPORTANT: Set SECRET_KEY in Render Environment (do NOT hardcode)
SECRET_KEY = os.getenv("SECRET_KEY", "dev-only-secret-key-change-me")

# DEBUG must be False in production
DEBUG = os.getenv("DEBUG", "False") == "True"

# Comma-separated hosts in env: "a.onrender.com,example.com"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# CSRF trusted origins for https domains (comma-separated)
# Example: "https://yourapp.onrender.com,https://yourdomain.com"
CSRF_TRUSTED_ORIGINS = (
    os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if os.getenv("CSRF_TRUSTED_ORIGINS")
    else []
)

# If behind Render/Reverse proxy and you enable HTTPS:
# Render terminates TLS and forwards proto header
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Optional: Turn these on when HTTPS is working (recommended)
# Use env to control so you can safely test
SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "False") == "True"
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "False") == "True"
CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", "False") == "True"

# HSTS (only enable after HTTPS is confirmed)
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv("SECURE_HSTS_INCLUDE_SUBDOMAINS", "False") == "True"
SECURE_HSTS_PRELOAD = os.getenv("SECURE_HSTS_PRELOAD", "False") == "True"

# ----------------------
# APPLICATIONS
# ----------------------
INSTALLED_APPS = [
    "jazzmin",  # must be before admin
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Your apps
    "listings",
    "pages",
    "accounts.apps.AccountsConfig",

    # If you use CORS, keep this (you already installed it)
    "corsheaders",
]

# ----------------------
# MIDDLEWARE (Correct order)
# ----------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    # If using CORS, it should be high in the stack
    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    "pages.middleware.SiteVisitMiddleware",
]

# ----------------------
# URLS / TEMPLATES / WSGI
# ----------------------
ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "pages.context_processors.site_stats",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# ----------------------
# DATABASE (Render Postgres via DATABASE_URL)
# ----------------------
# IMPORTANT: Set DATABASE_URL in Render Environment
DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL"),
        conn_max_age=600,
    )
}

# ----------------------
# EMAIL (ENV BASED — no secrets in code)
# ----------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Scholarify <no-reply@scholarify.com>")
CONTACT_RECEIVER_EMAIL = os.getenv("CONTACT_RECEIVER_EMAIL", EMAIL_HOST_USER)
SERVER_EMAIL = os.getenv("SERVER_EMAIL", "server@scholarify.com")

SITE_ID = 1
SITE_NAME = os.getenv("SITE_NAME", "Scholarify")

# Use Render public URL in production if you want links in emails
SITE_URL = os.getenv("SITE_URL", "http://localhost:8000")

# ----------------------
# PASSWORD VALIDATION
# ----------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ----------------------
# INTERNATIONALIZATION (EN + PASHTO)
# ----------------------
LANGUAGE_CODE = "en"

EXTRA_LANG_INFO = {
    "ps": {
        "bidi": True,
        "code": "ps",
        "name": "Pashto",
        "name_local": "پښتو",
    }
}
django.conf.locale.LANG_INFO.update(EXTRA_LANG_INFO)

LANGUAGES = [
    ("en", _("English")),
    ("ps", _("Pashto")),
]

USE_I18N = True
USE_L10N = True

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = "Asia/Kabul"
USE_TZ = True

# ----------------------
# STATIC & MEDIA (WhiteNoise + collectstatic)
# ----------------------
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# If you have a /static folder in repo, keep this (safe)
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []

# Recommended for WhiteNoise caching
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ----------------------
# AUTH
# ----------------------
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# ----------------------
# SESSION
# ----------------------
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_SAVE_EVERY_REQUEST = True

# ----------------------
# DEFAULT PK
# ----------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ----------------------
# LOGGING
# ----------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": "WARNING"},
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}

# ----------------------
# CORS (only if you actually need it)
# ----------------------
# For production, set CORS_ALLOWED_ORIGINS in Render if needed
# Example: "https://your-frontend.com"
CORS_ALLOWED_ORIGINS = (
    os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
    if os.getenv("CORS_ALLOWED_ORIGINS")
    else []
)
